spring.application.name=presentationGenerator
spring.datasource.url=jdbc:postgresql://localhost:5432/presentation
spring.datasource.username=postgres
spring.datasource.password=ramezrammeh
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=YZcF0RFaZxvWW1k5+KPqfAHp1Y3uwZd3FSXKLPnJdeRGY9mp2Ju06T6W7FM8WhC6kQZfSbdskRr4WJ7DqNQzTA==
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
upload.dir=uploads
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
gemini.api.key=AIzaSyDfCkYByZT7vNoLQ7YSGmPu_AFN95btSyA
